"""Package the physrnet package plus one experiment script into a standalone
Kaggle GPU kernel (same pattern as holon's build_script_kernel.py).

Usage:
    python build_kaggle_kernel.py --script exp/psn1_kaggle_nmi.py --name psn1-universal-nmi --gpu
    kaggle kernels push -p kernel/psn1-universal-nmi
"""
import argparse
import base64
import json
import pathlib
import zlib

ROOT = pathlib.Path(__file__).parent

SRC = [
    "physrnet/__init__.py",
    "physrnet/model_universal.py",
    "physrnet/e3_equivariant.py",
    "physrnet/attention_reasoning.py",
    "physrnet/conservation.py",
    "physrnet/pinn.py",
    "physrnet/datasets.py",
    "physrnet/physics/__init__.py",
    "physrnet/physics/fluids.py",
    "physrnet/physics/electromagnetism.py",
    "physrnet/physics/quantum.py",
    "physrnet/physics/thermodynamics.py",
    "physrnet/physics/relativistic.py",
]

TEMPLATE = '''"""PSN-1 kernel -- generated by build_kaggle_kernel.py, do not edit.
script: {script}
"""
import base64, json, os, pathlib, subprocess, sys, time, zlib

BLOB = "{blob}"
ARGS = {args}
WORK = pathlib.Path("/kaggle/working") if pathlib.Path("/kaggle").exists() else pathlib.Path(".").resolve()
SRCDIR = WORK / "src"
files = json.loads(zlib.decompress(base64.b64decode(BLOB)).decode("utf-8"))
for rel, txt in files.items():
    p = SRCDIR / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(txt, encoding="utf-8")
print("unpacked", len(files), "files", flush=True)
# fix CUDA compat on T4: Kaggle preinstalls cu128, T4 needs cu121
import subprocess as _sp
_sp.run([sys.executable, "-m", "pip", "install", "--quiet",
         "torch==2.5.1", "--index-url", "https://download.pytorch.org/whl/cu121"],
        check=True)
print("torch reinstalled for cu121", flush=True)

import torch
print("torch", torch.__version__, "cuda", torch.cuda.is_available(),
      "cpus", os.cpu_count(), flush=True)

env = dict(os.environ, PYTHONPATH=str(SRCDIR), OMP_NUM_THREADS="{th}",
           MKL_NUM_THREADS="{th}")
cmd = [sys.executable, str(SRCDIR / "{script}")] + ARGS
print("run", " ".join(cmd), flush=True)
rc = subprocess.run(cmd, cwd=str(SRCDIR), env=env).returncode
print("rc", rc, flush=True)
import glob
for pat in ("*.json", "*.gif", "*.png", "*.pt", "*.html", "*.csv"):
    for f in (SRCDIR / "results").glob(pat):
        (WORK / f.name).write_bytes(f.read_bytes())
        print("saved", f.name, f.stat().st_size, flush=True)
'''

ap = argparse.ArgumentParser()
ap.add_argument("--script", required=True)
ap.add_argument("--name", required=True)
ap.add_argument("--arg", action="append", default=[])
ap.add_argument("--extra", action="append", default=[])
ap.add_argument("--threads", type=int, default=2)
ap.add_argument("--gpu", action="store_true")
a = ap.parse_args()

files = {f: (ROOT / f).read_text(encoding="utf-8") for f in SRC + a.extra}
files[a.script] = (ROOT / a.script).read_text(encoding="utf-8")
blob = base64.b64encode(zlib.compress(json.dumps(files).encode("utf-8"), 9)).decode("ascii")
body = TEMPLATE.format(script=a.script, blob=blob, args=json.dumps(a.arg), th=a.threads)
d = ROOT / "kernel" / a.name
d.mkdir(parents=True, exist_ok=True)
(d / f"{a.name}.py").write_text(body, encoding="utf-8")
(d / "kernel-metadata.json").write_text(json.dumps(
    {"id": f"sehajrsingh/{a.name}", "title": a.name, "code_file": f"{a.name}.py",
     "language": "python", "kernel_type": "script", "is_private": True,
     "enable_gpu": bool(a.gpu), "enable_internet": bool(a.gpu),
     "dataset_sources": [], "competition_sources": [], "kernel_sources": []}, indent=2))
print("built", d, len(body), "bytes")
